# Generated by Django 4.1 on 2022-11-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0005_rename_investigator_article_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='investigator',
        ),
    ]
